swagger: '2.0'
info:
  title: Cheqd - Tendermint RPC
  description: 'A Tendermint RPC for state queries, write transactions'
  version: 1.0.0

paths:
  /getDid:
    get:
      tags:
        - Query
      summary: return DID
      operationId: returnDid
      description: |
        Return DID Document from the ledger by DID
      produces:
        - application/json
      parameters:
        - in: query
          name: id
          description: id from DID Document. Fully qualified DID
          required: true
          type: string
      responses:
        200:
          description: DID Document
          schema:
            $ref: '#/definitions/StateValue'
        400:
          description: bad input parameter

  /createDid:
    post:
      tags:
        - admins
      summary: adds an inventory item
      operationId: addInventory
      description: Adds an item to the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: inventoryItem
          description: Inventory item to add
          schema:
            $ref: '#/definitions/MsgCreateDid'
      responses:
        201:
          description: item created
          schema:
            $ref: '#/definitions/MsgCreateDidResponse'
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists

  /updateDid:
    post:
      tags:
        - admins
      summary: adds an inventory item
      operationId: updateInventory
      description: Adds an item to the system
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: inventoryItem
          description: Inventory item to add
          schema:
            $ref: '#/definitions/MsgUpdateDid'
      responses:
        201:
          description: item created
          schema:
            $ref: '#/definitions/MsgUpdateDidResponse'
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists
definitions:


  SignInfo:
    required:
      - verification_method_id
      - signature
    properties:
      verificationMethodId:
        type: string
        example: ACME Corporation
      signature:
        type: string
        example:  https://www.acme-corp.com
  MsgCreateDid:
    type: object
    required:
      - payload
      - signatures
    properties:
      payload:
        $ref: '#/definitions/MsgCreateDidPayload'
      signatures:
        type: array
        items:
          $ref: '#/definitions/SignInfo'

  MsgCreateDidPayload:
    required:
      - context
      - id
      - controller
      - verificationMethod
      - authentication
      - assertionMethod
      - capabilityInvocation
      - capabilityDelegation
      - keyAgreement
      - alsoKnownAs
      - service
    properties:
      context:
        type: array
        items:
          type: string
      id:
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB
      verificationMethod:
        type: array
        items:
          $ref: '#/definitions/VerificationMethod'
      controller:
        type: array
        items:
          type: string
      authentication:
        type: array
        items:
          type: string
      assertionMethod:
        type: array
        items:
          type: string
      capabilityInvocation:
        type: array
        items:
          type: string
      capabilityDelegation:
        type: array
        items:
          type: string
      keyAgreement:
        type: array
        items:
          type: string
      alsoKnownAs:
        type: array
        items:
          type: string
      service:
        type: array
        items:
          $ref: '#/definitions/Service'

  MsgCreateDidResponse:
    required:
      - id
    properties:
      id:
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB


  MsgUpdateDid:
    type: object
    required:
      - payload
      - signatures
    properties:
      payload:
        $ref: '#/definitions/MsgUpdateDidPayload'
      signatures:
        type: array
        items:
          $ref: '#/definitions/SignInfo'


  MsgUpdateDidPayload:
    required:
      - context
      - id
      - controller
      - verificationMethod
      - authentication
      - assertionMethod
      - capabilityInvocation
      - capabilityDelegation
      - keyAgreement
      - alsoKnownAs
      - service
      - versionId
    properties:
      context:
        type: array
        items:
          type: string
      id:
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB
      verificationMethod:
        type: array
        items:
          $ref: '#/definitions/VerificationMethod'
      controller:
        type: array
        items:
          type: string
      authentication:
        type: array
        items:
          type: string
      assertionMethod:
        type: array
        items:
          type: string
      capabilityInvocation:
        type: array
        items:
          type: string
      capabilityDelegation:
        type: array
        items:
          type: string
      keyAgreement:
        type: array
        items:
          type: string
      alsoKnownAs:
        type: array
        items:
          type: string
      service:
        type: array
        items:
          $ref: '#/definitions/Service'
      versionId:
        type: string
        example: 1B3B00849B4D50E8FCCF50193E35FD6CA5FD4686ED6AD8F847AC8C5E466CFD3E

  MsgUpdateDidResponse:
    required:
      - id
    properties:
      id:
        type: string
        example: did:cheqd:testnet:6cgbu8ZPoWTnR5Rv5JcSMB


  StateValue:
    required:
      - data
      - metadata
    properties:
      data:
        type: object
      metadata:
        $ref: '#/definitions/Metadata'

  Metadata:
    required:
      - created
      - updated
      - deactivated
      - versionId
    properties:
      created:
        type: string
        example: 2020-12-20T19:17:47Z
      updated:
        type: string
        example: 2020-12-20T19:17:47Z
      deactivated:
        type: boolean
        example: false
      versionId:
        type: string
        example: 1B3B00849B4D50E8FCCF50193E35FD6CA5FD4686ED6AD8F847AC8C5E466CFD3E

  Service:
    required:
      - id
      - type
      - serviceEndpoint
    properties:
      id:
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#linked-domain
      type:
        type: string
        example: LinkedDomains
      serviceEndpoint:
        type: string
        example: https://bar.example.com

  VerificationMethod :
    required:
      - id
      - type
      - controller
      - publicKeyJwk
      - publicKeyMultibase
    properties:
      id:
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue#key-0
      type:
        type: string
        example: Ed25519VerificationKey2020
      controller:
        type: string
        example: did:cheqd:mainnet:N22KY2Dyvmuu2PyyqSFKue
      publicKeyJwk:
        type: object
      publicKeyMultibase:
        type: string
        example: zAKJP3f7BD6W4iWEQ9jwndVTCBq8ua2Utt8EEjJ6Vxsf